### ISSUE TITLE
Issue with rendering of some media

### ISSUE THREAD

**Issue by antho1404** [liteflow-labs/starter-kit#316]
Some media are not displayed correctly.
For example, the NFT of this platform has an error while rendering.

https://animoca.demo.liteflow.com/tokens/137-0x9d305a42a3975ee4c1c57555bed5919889dce63f-103704

**Comment by NicolasMahe** [comment]
It seems to work without issue. This may have been fixed. @antho1404  Can you double check and close this issue if it's the case.

**Comment by antho1404** [comment]
The issue is still here. Somehow this token works now but another one from the same collections doesn't https://animoca.demo.liteflow.com/tokens/137-0x9d305a42a3975ee4c1c57555bed5919889dce63f-100000

Note: that might be a collection issue

**Comment by antho1404** [comment]
Closing, this is definitely a collection issue, the metadata are not accessible
